DATASET:
  NAME: "MVSAMultiple"
  ROOT: "datasets"

INPUT:
  SIZE: (384, 384)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_flip"]
  CROP_PADDING: 4

DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 16
    N_DOMAIN: 0
    N_INS: 16
    SAMPLER: "RandomSampler"
  TEST:
    BATCH_SIZE: 32
    SAMPLER: "SequentialSampler"
  NUM_WORKERS: 4

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"

TRAINER:
  NAME: "MaPLe"
  MAPLE:
    N_CTX: 16
    C_SCALE: 1.0
    C_INIT: "uniform"
    PREC: "fp16"





