DATASET:
  NAME: "MVSASingle"
  ROOT: "datasets"  # Path to the parent folder containing MVSA_Single/

INPUT:
  SIZE: [224, 224]
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 32
  TEST:
    BATCH_SIZE: 100
  NUM_WORKERS: 4

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"

